<a href="https://colab.research.google.com/github/Johar98/university_project/blob/master/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.424, tf.float64)
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [3]:
rank1_tensor = tf.Variable(["test","ok","johar"], tf.string)
rank2_tensor = tf.Variable([["test","book",],["rank","dimensions"]], tf.string)
rank2_tensor.shape

TensorShape([2, 2])

In [5]:
tensor1 = tf.ones([1,2,3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3,-1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
